<?php /* Smarty version 2.6.0, created on 2010-04-23 01:23:13
         compiled from blank.tpl */ ?>
<div align="center"><h1><?php echo $this->_tpl_vars['maintitle']; ?>
</h1></div>
<strong>Welcome to <?php echo $this->_tpl_vars['package']; ?>
!</strong><br />
<br />
This documentation was generated by <a href="<?php echo $this->_tpl_vars['phpdocwebsite']; ?>
">phpDocumentor v<?php echo $this->_tpl_vars['phpdocversion']; ?>
</a>
<br />
